INSERT INTO `labtest` (`labid`, `test`, `typeoftest`, `subtype`, `normalmin`, `normalmax`, `flag`, `price`) VALUES
(150, 'Roentgenological', 'KUB', 'NA', 'NA', '', '', 380),
(151, 'Roentgenological', 'PELVIS AP', 'NA', 'NA', '', '', 250),
(152, 'Roentgenological', 'PELVIS APL', 'NA', 'NA', '', '', 500),
(153, 'Roentgenological', 'SPINE', 'LS Right and Left Oblique', 'NA', '', '', 490),
(154, 'Roentgenological', 'SPINE', 'Lumbosacral APL', 'NA', '', '', 750),
(155, 'Roentgenological', 'SPINE', 'Thoracolumbar APL', 'NA', '', '', 750),
(156, 'Roentgenological', 'SPINE', 'Thoracolumbar AP', 'NA', '', '', 375),
(157, 'Roentgenological', 'SPINE', 'Cervical APL with Right and Left Oblique', 'NA', '', '', 980),
(158, 'Roentgenological', 'SPINE', 'Cervical APL', 'NA', '', '', 490),
(159, 'Roentgenological', 'SPINE', 'Cervical AP', 'NA', '', '', 250),
(160, 'Roentgenological', 'Air Cells', 'Mastoid Series', 'NA', '', '', 1000),
(161, 'Roentgenological', 'PNS', 'Waters View', 'NA', '', '', 250),
(162, 'Roentgenological', 'SKULL', 'Mandible APO', 'NA', '', '', 450),
(163, 'Roentgenological', 'PNS', 'Paranasal Sinuses (PNS)', 'NA', '', '', 800),
(164, 'Roentgenological', 'SKULL', 'Soft Tissue', 'NA', '', '', 250),
(165, 'Roentgenological', 'SKULL', 'Towns View', 'NA', '', '', 250),
(166, 'Roentgenological', 'SKULL', 'APL', 'NA', '', '', 480),
(167, 'Roentgenological', 'Chest', 'LATERAL DECUBITUS', 'NA', '', '', 270),
(168, 'Roentgenological', 'SKULL', 'AP, PA', 'NA', '', '', 250),
(169, 'Roentgenological', 'Chest', 'APICOLORDOTIC VIEW', 'NA', '', '', 250),
(170, 'Roentgenological', 'Chest', 'PAL, APL', 'NA', '', '', 470),
(171, 'Roentgenological', 'Chest', 'Bucky', 'NA', '', '', 300),
(172, 'Roentgenological', 'Chest', 'PA, AP', 'NA', '', '', 240),
(173, 'Roentgenological', 'Lower Extremities', 'PAL, APL, APO', 'NA', '', '', 390),
(174, 'Roentgenological', 'Lower Extremities', 'PA, AP, LAT, OBLIQUE', 'NA', '', '', 230),
(175, 'Roentgenological', 'Upper Extremities', 'PAL, APL, APO', 'NA', '', '', 350),
(176, 'Roentgenological', 'Upper Extremities', 'APL & OBL', 'NA', '', '', 580),
(177, 'Roentgenological', 'Upper Extremities', 'PA, AP, LAT, OBLIQUE', 'NA', '', '', 230),
(178, 'Roentgenological', 'Upper Extremities', 'SHOULDER APO', 'NA', '', '', 400),
(179, 'Roentgenological', 'Upper Extremities', 'CLAVICLE APL', 'NA', '', '', 400);