INSERT INTO `labtest` (`labid`, `test`, `typeoftest`, `subtype`, `normalmin`, `normalmax`, `flag`, `price`) VALUES
(120, 'Ultrasound', 'CHEST', 'NA', 'NA', '', '', 1000),
(121, 'Ultrasound', 'CHEST (WITH MAKER)', 'NA', 'NA', '', '', 1400),
(122, 'Ultrasound', 'FETAL AGING', 'NA', 'NA', '', '', 600),
(123, 'Ultrasound', 'FETAL AGING (TWINS)', 'NA', 'NA', '', '', 800),
(124, 'Ultrasound', 'FETAL AGING WITH BIOPHYSICAL PROFIEL (BPP)', 'NA', 'NA', '', '', 900),
(125, 'Ultrasound', 'FETAL AGING WITH BIOPHYSICAL PROFIEL (BPP) (TWINS)', 'NA', 'NA', '', '', 1400),
(126, 'Ultrasound', 'PELVIS', 'NA', 'NA', '', '', 600),
(127, 'Ultrasound', 'HBT (6- 8 HRS FASTING)', 'NA', 'NA', '', '', 1200),
(128, 'Ultrasound', 'HBT/PANCREAS (6- 8 HRS FASTING)', 'NA', 'NA', '', '', 1300),
(129, 'Ultrasound', 'TRANSVAGINAL', 'NA', 'NA', '', '', 800),
(130, 'Ultrasound', 'TRANSRECTAL', 'NA', 'NA', '', '', 800),
(131, 'Ultrasound', 'WHOLE ABDOMEN (FULL BLADDER)', 'NA', 'NA', '', '', 1850),
(132, 'Ultrasound', 'UPPER ABDOMEN (6-8 HRS FASTING)', 'NA', 'NA', '', '', 1400),
(133, 'Ultrasound', 'LOWER ABDOMEN (FULL BLADDER)', 'NA', 'NA', '', '', 1200),
(134, 'Ultrasound', 'KIDNEY URINARY BLADDER (KUB)', 'NA', 'NA', '', '', 1200),
(135, 'Ultrasound', 'THYROID', 'NA', 'NA', '', '', 1200),
(136, 'Ultrasound', 'PROSTATE', 'NA', 'NA', '', '', 800),
(137, 'Ultrasound', 'SCROTAL', 'NA', 'NA', '', '', 1200),
(138, 'Ultrasound', 'BREAST', 'NA', 'NA', '', '', 1320),
(139, 'Ultrasound', 'MASS EVALUATION', 'NA', 'NA', '', '', 1200),
(140, 'Ultrasound', 'HBT WITH KIDNEYS (6-8 HRS FASTING)', 'NA', 'NA', '', '', 1600),
(141, 'Ultrasound', 'LIVER', 'NA', 'NA', '', '', 900),
(142, 'Ultrasound', 'KIDNEYS', 'NA', 'NA', '', '', 1000),
(143, 'Ultrasound', 'GALLBLADER', 'NA', 'NA', '', '', 600),
(144, 'Ultrasound', 'CRANIAL', 'NA', 'NA', '', '', 1200);