INSERT INTO `labtest` (`labid`, `test`, `typeoftest`, `subtype`, `normalmin`, `normalmax`, `flag`, `price`) VALUES
(6, 'Urinalysis', 'Physical Properties', 'Specific Gravity', 'NA', '', '', 100),
(5, 'Urinalysis', 'Physical Properties', 'pH', 'NA', '', '', 100),
(4, 'Urinalysis', 'Physical Properties', 'Transparency', 'NA', '', '', 10),
(3, 'Urinalysis', 'Physical Properties', 'Color', 'NA', '', '', 100),
(30, 'Urinalysis', 'Others:', 'Pregnancy Test::', 'NA', '', '', 100),
(29, 'Urinalysis', 'Cast', 'Crystals:', 'NA', '', '', 100),
(28, 'Urinalysis', 'Cast', 'Yeast Cells', 'NA', '', '', 100),
(27, 'Urinalysis', 'Cast', 'Mucus Threads', 'NA', '', '', 100),
(26, 'Urinalysis', 'Cast', 'Bacteria:', 'NA', '', '', 100),
(25, 'Urinalysis', 'Cast', 'Amorphous deposits:', 'NA', '', '', 100),
(24, 'Urinalysis', 'Cast', 'Squamous Epithelial Cells:', 'NA', '', '', 100),
(23, 'Urinalysis', 'Cast', 'Round Epithelial Cells:', 'NA', '', '', 100),
(22, 'Urinalysis', 'Cast', 'Coarse Granular:', 'NA', '', '', 100),
(21, 'Urinalysis', 'Cast', 'Fine Granular:', 'NA', '', '', 100),
(20, 'Urinalysis', 'Cast', 'Hyaline:', 'NA', '', '', 100),
(19, 'Urinalysis', 'Cast', 'Waxy:', 'NA', '', '', 100),
(18, 'Urinalysis', 'Cast', 'WBC:', 'NA', '', '', 100),
(17, 'Urinalysis', 'Cast', 'RBC:', 'NA', '', '', 100),
(16, 'Urinalysis', 'RBC Morphology', '    Swollen', 'NA', '', '', 100),
(15, 'Urinalysis', 'RBC Morphology', '   Shadow', 'NA', '', '', 100),
(13, 'Urinalysis', 'RBC Morphology', '   Dysmorphic', 'NA', '', '', 100),
(14, 'Urinalysis', 'RBC Morphology', '   Crenated', 'NA', '', '', 100),
(12, 'Urinalysis', 'RBC Morphology', '   Intact', 'NA', '', '', 100),
(10, 'Urinalysis', 'Microscopic Findings', 'RBC /hpf', 'NA', '', '', 100),
(9, 'Urinalysis', 'Microscopic Findings', 'Pus Cells /hpf', 'NA', '', '', 100),
(8, 'Urinalysis', 'Chemical Tests', 'Sugar', 'NA', '', '', 100),
(7, 'Urinalysis', 'Chemical Tests', 'Albumin', 'NA', '', '', 100);